copy Origins07_Launcher.exe Origins07_Customizer.exe
copy Origins07_Launcher.exe Origins07_DedicatedServer.exe
copy Origins07_Launcher.exe Origins07_Installer.exe
copy Origins07_Launcher.exe Origins07_PlaySolo.exe